# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('report_name', models.CharField(choices=[(b'CS', b'CS')], max_length=50)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportdata',
            unique_together=set([('channel_id', 'report_name')]),
        ),
    ]
