# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0002_auto_20180529_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='data',
            field=models.TextField(),
        ),
    ]
