# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApp', '0003_auto_20180529_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('channel_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='report_name',
            field=models.CharField(choices=[(b'CS', b'CS'), (b'VS', b'VS'), (b'VTS', b'VTS'), (b'CL', b'CL')], max_length=50),
        ),
    ]
