XXXXXXXXX XXXXX
XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXXX
  XXXX X XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX X
  XX X XXXXXXXXXX XXXXX X
  XXXX X XXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXX X
  XXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXX X
  X X XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX X
  XXXXXXX X XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX X
XXXXXXXX

XXXXXXXXX
    XXXXXXXXXXXXXXX XX XXXX XXXXXXXXXX
    XXXXX
        XXXXXXXX XXX XXX XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XX XXX XXXXXXX XX XXX XXXX XX XXX XXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX XX XXXX XXXXXX XXXXXXXXXXXX
        XXXXXXXXXX XXX XXXXXXXX
    XXXXXX
XXXXXXXXXX
